# Simple Keras Tests

### Import statements and assignment

In [1]:
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [2]:
# Loading
iris = load_iris()

# Assigning data and targets
X = iris.data
y = iris.target

In [3]:
# Cast y to one-hot coded vector
y = to_categorical(y)

In [4]:
# Split dataset into train and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=77)

In [5]:
# Scale data
scaler_object = MinMaxScaler()
scaler_object.fit(X_train)

scaled_X_train = scaler_object.transform(X_train)
scaled_X_test = scaler_object.transform(X_test)

## Create Model

In [6]:
model = Sequential()

model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [7]:
model.fit(scaled_X_train, y_train, epochs=150, verbose=2)

Epoch 1/150
 - 0s - loss: 1.0295 - accuracy: 0.3048
Epoch 2/150
 - 0s - loss: 1.0224 - accuracy: 0.3048
Epoch 3/150
 - 0s - loss: 1.0155 - accuracy: 0.3048
Epoch 4/150
 - 0s - loss: 1.0088 - accuracy: 0.4000
Epoch 5/150
 - 0s - loss: 1.0022 - accuracy: 0.5238
Epoch 6/150
 - 0s - loss: 0.9955 - accuracy: 0.5905
Epoch 7/150
 - 0s - loss: 0.9889 - accuracy: 0.6381
Epoch 8/150
 - 0s - loss: 0.9824 - accuracy: 0.6476
Epoch 9/150
 - 0s - loss: 0.9763 - accuracy: 0.6571
Epoch 10/150
 - 0s - loss: 0.9705 - accuracy: 0.6571
Epoch 11/150
 - 0s - loss: 0.9653 - accuracy: 0.6571
Epoch 12/150
 - 0s - loss: 0.9601 - accuracy: 0.6571
Epoch 13/150
 - 0s - loss: 0.9550 - accuracy: 0.6571
Epoch 14/150
 - 0s - loss: 0.9497 - accuracy: 0.6571
Epoch 15/150
 - 0s - loss: 0.9447 - accuracy: 0.6571
Epoch 16/150
 - 0s - loss: 0.9393 - accuracy: 0.6571
Epoch 17/150
 - 0s - loss: 0.9339 - accuracy: 0.6571
Epoch 18/150
 - 0s - loss: 0.9286 - accuracy: 0.6571
Epoch 19/150
 - 0s - loss: 0.9232 - accuracy: 0.6571
Ep

In [8]:
preds = model.predict_classes(scaled_X_test)
cf_matrix = confusion_matrix(y_test.argmax(axis=1), preds)

print(cf_matrix)
print(classification_report(y_test.argmax(axis=1), preds))
print(f"Accuracy: {accuracy_score(y_test.argmax(axis=1), preds).round(3)}")

[[13  0  0]
 [ 0 12  2]
 [ 0  2 16]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.86      0.86      0.86        14
           2       0.89      0.89      0.89        18

    accuracy                           0.91        45
   macro avg       0.92      0.92      0.92        45
weighted avg       0.91      0.91      0.91        45

Accuracy: 0.911


## Saving Keras Models

In [9]:
# saving
model.save('the_model.h5')

# importing
from keras.models import load_model
import_model = load_model('the_model.h5')

# working
import_model.predict_classes(scaled_X_test)

array([1, 2, 2, 1, 0, 2, 2, 1, 0, 1, 0, 2, 0, 0, 0, 2, 2, 2, 0, 1, 0, 2,
       2, 1, 2, 1, 2, 0, 1, 1, 1, 2, 0, 2, 2, 1, 1, 2, 1, 2, 0, 1, 0, 0,
       2])