# Simple Keras Tests

### Import statements and assignment

In [20]:
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense

In [4]:
# Loading
iris = load_iris()

# Assigning data and targets
X = iris.data
y = iris.target

In [8]:
# Cast y to one-hot coded vector
y = to_categorical(y)

In [10]:
# Split dataset into train and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=77)

In [15]:
# Scale data
scaler_object = MinMaxScaler()
scaler_object.fit(X_train)

scaled_X_train = scaler_object.transform(X_train)
scaled_X_test = scaler_object.transform(X_test)

## Create Model

In [18]:
model = Sequential()

model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_6 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.fit(scaled_X_train, y_train, epochs=150, verbose=2)

Epoch 1/150
 - 0s - loss: 1.0158 - accuracy: 0.3048
Epoch 2/150
 - 0s - loss: 1.0018 - accuracy: 0.3048
Epoch 3/150
 - 0s - loss: 0.9882 - accuracy: 0.3048
Epoch 4/150
 - 0s - loss: 0.9764 - accuracy: 0.3048
Epoch 5/150
 - 0s - loss: 0.9652 - accuracy: 0.3048
Epoch 6/150
 - 0s - loss: 0.9559 - accuracy: 0.3048
Epoch 7/150
 - 0s - loss: 0.9467 - accuracy: 0.3048
Epoch 8/150
 - 0s - loss: 0.9380 - accuracy: 0.3048
Epoch 9/150
 - 0s - loss: 0.9290 - accuracy: 0.3143
Epoch 10/150
 - 0s - loss: 0.9207 - accuracy: 0.3143
Epoch 11/150
 - 0s - loss: 0.9120 - accuracy: 0.3905
Epoch 12/150
 - 0s - loss: 0.9041 - accuracy: 0.4286
Epoch 13/150
 - 0s - loss: 0.8963 - accuracy: 0.4952
Epoch 14/150
 - 0s - loss: 0.8886 - accuracy: 0.5333
Epoch 15/150
 - 0s - loss: 0.8814 - accuracy: 0.5810
Epoch 16/150
 - 0s - loss: 0.8740 - accuracy: 0.5905
Epoch 17/150
 - 0s - loss: 0.8667 - accuracy: 0.6095
Epoch 18/150
 - 0s - loss: 0.8592 - accuracy: 0.6286
Epoch 19/150
 - 0s - loss: 0.8517 - accuracy: 0.6476
Ep

In [27]:
preds = model.predict_classes(scaled_X_test)
cf_matrix = confusion_matrix(y_test.argmax(axis=1), preds)

print(cf_matrix)
print(classification_report(y_test.argmax(axis=1), preds))
print(f"Accuracy: {accuracy_score(y_test.argmax(axis=1), preds).round(3)}")

[[13  0  0]
 [ 0 13  1]
 [ 0  4 14]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.76      0.93      0.84        14
           2       0.93      0.78      0.85        18

    accuracy                           0.89        45
   macro avg       0.90      0.90      0.90        45
weighted avg       0.90      0.89      0.89        45

Accuracy: 0.889


## Saving Keras Models

In [29]:
# saving
model.save('the_model.h5')

# importing
from keras.models import load_model
import_model = load_model('the_model.h5')

# working
import_model.predict_classes(scaled_X_test)

AttributeError: 'Sequential' object has no attribute 'predict_classses'